apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 459eb077-504e-4d21-93da-99551583d25f   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: kvozozturk       # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLDBNAME
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""
          objectAlias: SQL_DBNAME
                         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLUSER
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""              
          objectAlias: SQL_USER
        - |
          objectName: SQLPASSWORD
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
          objectAlias: SQL_PASSWORD
        - |
          objectName: SQLSERVER
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
          objectAlias: SQL_SERVER   
    tenantId: 5481298b-f7b3-4ce0-b953-0184faeded92                 # The tenant ID of the key vault